KEY_LEN: int
TWEAK_LEN: int

def validate_key(key: bytes) -> bytes: ...
def validate_tweak(tweak: bytes) -> bytes: ...
def derive_key(master: bytes, context: str) -> bytes: ...
def derive_tweak(master: bytes, context: str) -> bytes: ...
